# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""SANA-WM diffusion model integration."""

from vllm_omni.diffusion.models.sana_wm.camera_control import (
    SANA_WM_CAMERA_ERROR,
    SanaWmCameraCondition,
    build_plucker_condition,
)
from vllm_omni.diffusion.models.sana_wm.config import SanaWmConfig
from vllm_omni.diffusion.models.sana_wm.gated_deltanet_triton import (
    SANA_WM_DISABLE_TRITON_GDN_ENV,
    SANA_WM_GDN_ERROR,
    SANA_WM_REQUIRE_TRITON_GDN_ENV,
    BidirectionalGatedDeltaNetTriton,
    reference_bidirectional_gated_delta_net,
    triton_bidirectional_gated_delta_net_from_qkv,
)
from vllm_omni.diffusion.models.sana_wm.pipeline_sana_wm import (
    SANA_WM_CONFIG_FILE,
    SANA_WM_DEFAULT_NUM_FRAMES,
    SANA_WM_MODEL_ID,
    SANA_WM_OUTPUT_HEIGHT,
    SANA_WM_OUTPUT_WIDTH,
    SANA_WM_REFINER_CONNECTORS_CONFIG_FILE,
    SANA_WM_REFINER_CONNECTORS_WEIGHT_FILE,
    SANA_WM_REFINER_ROOT_ENV,
    SANA_WM_REFINER_TEXT_ENCODER_DIR,
    SANA_WM_REFINER_TEXT_ENCODER_INDEX_FILE,
    SANA_WM_REFINER_TRANSFORMER_CONFIG_FILE,
    SANA_WM_REFINER_TRANSFORMER_WEIGHT_FILE,
    SANA_WM_SCAFFOLD_ERROR,
    SANA_WM_STAGE1_DIT_FILE,
    SANA_WM_STAGE1_TEXT_ENCODER_ENV,
    SANA_WM_STAGE1_TEXT_ENCODER_FALLBACK_ID,
    SANA_WM_STAGE1_TEXT_ENCODER_ID,
    SANA_WM_VAE_CONFIG_FILE,
    SANA_WM_VAE_WEIGHT_FILE,
    SanaWmLocalPaths,
    SanaWmNativeParams,
    SanaWmPipeline,
    build_sana_wm_download_patterns,
    get_sana_wm_post_process_func,
    get_sana_wm_pre_process_func,
    resolve_or_download_sana_wm_checkpoint,
    resolve_sana_wm_local_paths,
    validate_sana_wm_local_paths,
)
from vllm_omni.diffusion.models.sana_wm.pipeline_sana_wm_two_stages import (
    SANA_WM_INPROCESS_REFINER_ARG,
    SANA_WM_INPROCESS_REFINER_STEPS_ARG,
    SanaWmTwoStagesPipeline,
)
from vllm_omni.diffusion.models.sana_wm.sana_wm_transformer import (
    SANA_WM_STAGE1_PROMPT_CHANNELS,
    SANA_WM_TRANSFORMER_FORWARD_ERROR,
    SanaWmCameraEmbedder,
    SanaWmStage1LoadReport,
    SanaWmTransformer3DModel,
)
from vllm_omni.diffusion.models.sana_wm.scheduling_sana_wm import (
    SANA_WM_DEFAULT_INFERENCE_FLOW_SHIFT,
    SanaWmFlowMatchScheduler,
    shift_flow_timestep,
)
from vllm_omni.diffusion.models.sana_wm.weight_mapping import (
    SANA_WM_STAGE1_PREFIX_MAP,
    normalize_sana_wm_stage1_weight_name,
)

__all__ = [
    "SANA_WM_CAMERA_ERROR",
    "SANA_WM_CONFIG_FILE",
    "SANA_WM_DEFAULT_NUM_FRAMES",
    "SANA_WM_DISABLE_TRITON_GDN_ENV",
    "SANA_WM_GDN_ERROR",
    "SANA_WM_INPROCESS_REFINER_ARG",
    "SANA_WM_INPROCESS_REFINER_STEPS_ARG",
    "SANA_WM_MODEL_ID",
    "SANA_WM_OUTPUT_HEIGHT",
    "SANA_WM_OUTPUT_WIDTH",
    "SANA_WM_REFINER_CONNECTORS_CONFIG_FILE",
    "SANA_WM_REFINER_CONNECTORS_WEIGHT_FILE",
    "SANA_WM_REFINER_TEXT_ENCODER_DIR",
    "SANA_WM_REFINER_TEXT_ENCODER_INDEX_FILE",
    "SANA_WM_REFINER_ROOT_ENV",
    "SANA_WM_REFINER_TRANSFORMER_CONFIG_FILE",
    "SANA_WM_REFINER_TRANSFORMER_WEIGHT_FILE",
    "SANA_WM_REQUIRE_TRITON_GDN_ENV",
    "SANA_WM_SCAFFOLD_ERROR",
    "SANA_WM_STAGE1_DIT_FILE",
    "SANA_WM_STAGE1_TEXT_ENCODER_ENV",
    "SANA_WM_STAGE1_TEXT_ENCODER_FALLBACK_ID",
    "SANA_WM_STAGE1_PREFIX_MAP",
    "SANA_WM_STAGE1_PROMPT_CHANNELS",
    "SANA_WM_STAGE1_TEXT_ENCODER_ID",
    "SANA_WM_TRANSFORMER_FORWARD_ERROR",
    "SANA_WM_VAE_CONFIG_FILE",
    "SANA_WM_VAE_WEIGHT_FILE",
    "SANA_WM_DEFAULT_INFERENCE_FLOW_SHIFT",
    "BidirectionalGatedDeltaNetTriton",
    "SanaWmCameraCondition",
    "SanaWmCameraEmbedder",
    "SanaWmConfig",
    "SanaWmFlowMatchScheduler",
    "SanaWmLocalPaths",
    "SanaWmNativeParams",
    "SanaWmStage1LoadReport",
    "SanaWmPipeline",
    "SanaWmTransformer3DModel",
    "SanaWmTwoStagesPipeline",
    "build_plucker_condition",
    "build_sana_wm_download_patterns",
    "get_sana_wm_pre_process_func",
    "get_sana_wm_post_process_func",
    "normalize_sana_wm_stage1_weight_name",
    "resolve_or_download_sana_wm_checkpoint",
    "resolve_sana_wm_local_paths",
    "reference_bidirectional_gated_delta_net",
    "shift_flow_timestep",
    "triton_bidirectional_gated_delta_net_from_qkv",
    "validate_sana_wm_local_paths",
]
