# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""SANA-WM diffusion model integration."""

from vllm_omni.diffusion.models.sana_wm.camera_control import (
    SANA_WM_CAMERA_ERROR,
    SanaWmCameraCondition,
    build_plucker_condition,
)
from vllm_omni.diffusion.models.sana_wm.config import SanaWmConfig
from vllm_omni.diffusion.models.sana_wm.gated_deltanet_triton import (
    SANA_WM_GDN_ERROR,
    BidirectionalGatedDeltaNetTriton,
)
from vllm_omni.diffusion.models.sana_wm.official_backend import (
    SANA_WM_OFFICIAL_BACKEND_ERROR,
    SANA_WM_OFFICIAL_REPO_ENV,
    SANA_WM_OFFICIAL_SCRIPT,
    SanaWmOfficialRunResult,
    build_sana_wm_official_command,
    find_sana_wm_official_script,
    get_sana_wm_official_repo_path,
    is_sana_wm_official_backend_available,
    is_sana_wm_official_backend_requested,
    require_sana_wm_official_script,
    run_sana_wm_official_backend,
)
from vllm_omni.diffusion.models.sana_wm.pipeline_sana_wm import (
    SANA_WM_CONFIG_FILE,
    SANA_WM_DEFAULT_NUM_FRAMES,
    SANA_WM_MODEL_ID,
    SANA_WM_OUTPUT_HEIGHT,
    SANA_WM_OUTPUT_WIDTH,
    SANA_WM_REFINER_CONNECTORS_CONFIG_FILE,
    SANA_WM_REFINER_CONNECTORS_WEIGHT_FILE,
    SANA_WM_REFINER_TEXT_ENCODER_DIR,
    SANA_WM_REFINER_TEXT_ENCODER_INDEX_FILE,
    SANA_WM_REFINER_TRANSFORMER_CONFIG_FILE,
    SANA_WM_REFINER_TRANSFORMER_WEIGHT_FILE,
    SANA_WM_SCAFFOLD_ERROR,
    SANA_WM_STAGE1_DIT_FILE,
    SANA_WM_STAGE1_TEXT_ENCODER_ID,
    SANA_WM_VAE_CONFIG_FILE,
    SANA_WM_VAE_WEIGHT_FILE,
    SanaWmLocalPaths,
    SanaWmPipeline,
    build_sana_wm_download_patterns,
    get_sana_wm_pre_process_func,
    get_sana_wm_post_process_func,
    resolve_or_download_sana_wm_checkpoint,
    resolve_sana_wm_local_paths,
    validate_sana_wm_local_paths,
)
from vllm_omni.diffusion.models.sana_wm.pipeline_sana_wm_two_stages import (
    SanaWmTwoStagesPipeline,
)
from vllm_omni.diffusion.models.sana_wm.sana_wm_transformer import (
    SANA_WM_TRANSFORMER_FORWARD_ERROR,
    SanaWmStage1LoadReport,
    SanaWmTransformer3DModel,
)
from vllm_omni.diffusion.models.sana_wm.weight_mapping import (
    SANA_WM_STAGE1_PREFIX_MAP,
    normalize_sana_wm_stage1_weight_name,
)

__all__ = [
    "SANA_WM_CAMERA_ERROR",
    "SANA_WM_CONFIG_FILE",
    "SANA_WM_DEFAULT_NUM_FRAMES",
    "SANA_WM_GDN_ERROR",
    "SANA_WM_MODEL_ID",
    "SANA_WM_OFFICIAL_BACKEND_ERROR",
    "SANA_WM_OFFICIAL_REPO_ENV",
    "SANA_WM_OFFICIAL_SCRIPT",
    "SANA_WM_OUTPUT_HEIGHT",
    "SANA_WM_OUTPUT_WIDTH",
    "SANA_WM_REFINER_CONNECTORS_CONFIG_FILE",
    "SANA_WM_REFINER_CONNECTORS_WEIGHT_FILE",
    "SANA_WM_REFINER_TEXT_ENCODER_DIR",
    "SANA_WM_REFINER_TEXT_ENCODER_INDEX_FILE",
    "SANA_WM_REFINER_TRANSFORMER_CONFIG_FILE",
    "SANA_WM_REFINER_TRANSFORMER_WEIGHT_FILE",
    "SANA_WM_SCAFFOLD_ERROR",
    "SANA_WM_STAGE1_DIT_FILE",
    "SANA_WM_STAGE1_PREFIX_MAP",
    "SANA_WM_STAGE1_TEXT_ENCODER_ID",
    "SANA_WM_TRANSFORMER_FORWARD_ERROR",
    "SANA_WM_VAE_CONFIG_FILE",
    "SANA_WM_VAE_WEIGHT_FILE",
    "BidirectionalGatedDeltaNetTriton",
    "SanaWmCameraCondition",
    "SanaWmConfig",
    "SanaWmLocalPaths",
    "SanaWmOfficialRunResult",
    "SanaWmStage1LoadReport",
    "SanaWmPipeline",
    "SanaWmTransformer3DModel",
    "SanaWmTwoStagesPipeline",
    "build_plucker_condition",
    "build_sana_wm_official_command",
    "build_sana_wm_download_patterns",
    "find_sana_wm_official_script",
    "get_sana_wm_pre_process_func",
    "get_sana_wm_post_process_func",
    "get_sana_wm_official_repo_path",
    "is_sana_wm_official_backend_available",
    "is_sana_wm_official_backend_requested",
    "normalize_sana_wm_stage1_weight_name",
    "resolve_or_download_sana_wm_checkpoint",
    "resolve_sana_wm_local_paths",
    "require_sana_wm_official_script",
    "run_sana_wm_official_backend",
    "validate_sana_wm_local_paths",
]
